In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])

In [3]:
a.shape

(5,)

In [4]:
b = np.array([[1,2,3,4],[5,6,7,8]])

In [5]:
b.shape

(2, 4)

In [9]:
c = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [10]:
n_shape = c.reshape(4,3)

In [11]:
c.shape

(12,)

In [12]:
n_shape.shape

(4, 3)

In [13]:
d_arr = np.array([[1,2,3,4],[5,6,7,8]])

In [14]:
flatten_arr = d_arr.reshape(-1)

In [15]:
flatten_arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
# Array Indexing
f = np.array([1,2,3,4,5])
print(f[0])

1


In [18]:
e = np.array([[1,2,3,4,5], [6,7,8,9,10]])

In [20]:
e

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [21]:
print(e[1,4])

10


In [22]:
# Iteration

arr1 = np.array([1,2,3,4,5,6])

for x in arr1:
    print(x)

1
2
3
4
5
6


In [24]:
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,11]])

for x in arr2:
    for y in x:
        print(y)

1
2
3
4
5
6
7
8
9
11


In [28]:
# Array Slicing
sly = np.array([1,2,3,4,5])

In [29]:
sly

array([1, 2, 3, 4, 5])

In [30]:
sly[1:4]

array([2, 3, 4])

In [31]:
dtw_arr = np.array([[1,2,3,4,5],[6,7,8,9,11]])

In [32]:
dtw_arr[1,1:4]

array([7, 8, 9])

In [35]:
# Searching and sorting
ss = np.array([1,4,3,2,5])

In [36]:
search_it = np.where(ss == 4)
print("SEARCH ", search_it)


sort_it = np.sort(ss)
print("SORT ", sort_it)

SEARCH  (array([1], dtype=int64),)
SORT  [1 2 3 4 5]
